version: "3"
services:
  microservice:
    container_name: backk-example-project
    restart: always
    build: .
    env_file:
      - .env.ci
    ports:
      - "${PORT}:${PORT}"
    links:
# TODO: choose your data store
      - mongodb
#      - postgresql
#      - mysql
#      - mariadb
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
#  mysql:
#    container_name: mysql
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - "${MYSQL_PORT}:${MYSQL_PORT}"
#  mariadb:
#    container_name: mariadb
#    image: mariadb
#    restart: always
#    environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - "${MYSQL_PORT}:${MYSQL_PORT}"
#  postgresql:
#    container_name: postgres
#    image: postgres
#    restart: always
#    environment:
#       POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
#    ports:
#      - "${POSTGRESQL_PORT}:${POSTGRESQL_PORT}"
