openapi: 3.0.3
info:
  title: backk-starter API
  description: ""
  version: 1.0.0
servers:
  - url: http://localhost:3001/backk-starter.default
    description: Local development server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    openId: null
  schemas: {}
security:
  - bearerAuth: []
paths: {}
