environmentType: production

deployment:
  pod:
    annotations: {}
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 2000
      fsGroup: 3000
      allowPrivilegeEscalation: false
    imagePullSecrets: []
    container:
      image:
        registry: ''
        repository: backk-example-project
        tag: ''
      imagePullPolicy: Always
      resources:
        development:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        integration:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        production:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 1
            memory: 512Mi
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }

hpa:
  minReplicas: 2
  maxReplicas: 1000
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  shouldCreate: true
  annotations: {}


