{{- if .Values.service.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backk-example-microservice.fullname" . }}
  labels:
    {{- include "backk-example-microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "backk-example-microservice.selectorLabels" . | nindent 4 }}
{{- end }}
